Fix "AttributeError: 'NoneType' object has no attribute 'replace'" when jmprint() called with None as msg
Bug introduced with c139067be48377dba9d29fc45c1424d199676a9a