Fix "AttributeError: 'NoneType' object has no attribute 'replace'" when jmprint() called with None as msg Bug introduced with c139067be48377dba9d29fc45c1424d199676a9a Return empty string instead of None from wallet_fetch_history() as wallet-tool.py prints the result all wallet_tool_main return vals as string